version: '3.3'

services:
  # PostgreSQL service
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: reseller_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  # Reseller Registration Service
  reseller-registration-service:
    build: ./reseller-registration-service
    container_name: reseller-registration-service
    ports:
      - "8081:8080"
   environment:
     - SPRING_PROFILES_ACTIVE=test
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/reseller_test_db
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - backend

  # Order Receiving Service
  order-receiving-service:
    build: ./order-receiving-service
    container_name: order-receiving-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - backend

  # Order Processing Service
  order-processing-service:
    build: ./order-processing-service
    container_name: order-processing-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_processing_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
